// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFgGNBA4HcwUQypBReXjxxoBV5WkpRdR4',
    appId: '1:880274782556:web:63c773dce2b03622b16999',
    messagingSenderId: '880274782556',
    projectId: 'college-management-d1c63',
    authDomain: 'college-management-d1c63.firebaseapp.com',
    storageBucket: 'college-management-d1c63.firebasestorage.app',
    measurementId: 'G-EJQ4ZEYNB9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYcIql3ihTkdsN3uVHaLx5jyX2qLMxB0',
    appId: '1:880274782556:ios:7532f4476404be5fb16999',
    messagingSenderId: '880274782556',
    projectId: 'college-management-d1c63',
    storageBucket: 'college-management-d1c63.firebasestorage.app',
    iosBundleId: 'com.example.collegeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYcIql3ihTkdsN3uVHaLx5jyX2qLMxB0',
    appId: '1:880274782556:ios:7532f4476404be5fb16999',
    messagingSenderId: '880274782556',
    projectId: 'college-management-d1c63',
    storageBucket: 'college-management-d1c63.firebasestorage.app',
    iosBundleId: 'com.example.collegeManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFgGNBA4HcwUQypBReXjxxoBV5WkpRdR4',
    appId: '1:880274782556:web:852376edc8fec11cb16999',
    messagingSenderId: '880274782556',
    projectId: 'college-management-d1c63',
    authDomain: 'college-management-d1c63.firebaseapp.com',
    storageBucket: 'college-management-d1c63.firebasestorage.app',
    measurementId: 'G-H75KTYBQXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJrLKPxxdsVjP2jw_wWH_7uO6r-vcMOSk',
    appId: '1:880274782556:android:b2bdc8cf33e8cd65b16999',
    messagingSenderId: '880274782556',
    projectId: 'college-management-d1c63',
    storageBucket: 'college-management-d1c63.firebasestorage.app',
  );

}